"""把 vrmmon 装进 PATH，之后在任意终端直接敲 `vrmmon` 即可启动。

**优先装到本来就在 PATH 里的目录**（Python 的 Scripts，pip 装命令行工具就用它）。
原因：新追加进 PATH 的目录对**已经在运行的 Explorer 不可见**，而用户新开的终端
是从 Explorer 继承环境的——注册表改对了，终端里照样找不到命令。只有目标目录
原本就在 PATH 里，装完立刻就能用。

于是大多数情况下本脚本**根本不修改 PATH**。确实需要改时，也严格保持原来的
注册表类型（用户 PATH 常是 REG_EXPAND_SZ 且含 %USERPROFILE% 这类变量引用）。

用法：
    python tools\\install_shortcut.py            # 安装
    python tools\\install_shortcut.py --uninstall # 卸载
    python tools\\install_shortcut.py --show      # 只看不改
"""

from __future__ import annotations

import argparse
import ctypes
import os
import sys
import winreg
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

from vrmmon import shortcut  # noqa: E402

ENV_KEY = r"Environment"
BACKUP = ROOT / "path-backup.txt"

#: 启动器内容保持纯 ASCII：cmd 按 OEM 代码页读 .cmd，中文容易出问题
SHIM_TEMPLATE = """@echo off
rem vrmmon launcher - generated by tools\\install_shortcut.py
rem Re-run that script if the project is moved.
setlocal
set "PY={python}"
if not exist "%PY%" set "PY=python"
"%PY%" "{cli}" %*
exit /b %ERRORLEVEL%
"""


def read_user_path() -> tuple[str, int]:
    """返回 (未展开的原始值, 注册表类型)。"""
    with winreg.OpenKey(winreg.HKEY_CURRENT_USER, ENV_KEY, 0, winreg.KEY_READ) as key:
        try:
            # QueryValueEx 不展开 REG_EXPAND_SZ，正是我们要保留的原始文本
            value, kind = winreg.QueryValueEx(key, "Path")
        except FileNotFoundError:
            return "", winreg.REG_EXPAND_SZ
    return value, kind


def write_user_path(value: str, kind: int) -> None:
    with winreg.OpenKey(winreg.HKEY_CURRENT_USER, ENV_KEY, 0,
                        winreg.KEY_READ | winreg.KEY_WRITE) as key:
        winreg.SetValueEx(key, "Path", 0, kind, value)


def entries_of(raw: str) -> list[str]:
    return [part for part in raw.split(";") if part.strip()]


def same_path(a: str, b: str) -> bool:
    return a.strip().rstrip("\\").lower() == b.strip().rstrip("\\").lower()


def broadcast_change() -> None:
    """通知资源管理器环境变量已变。"""
    try:
        user32 = ctypes.WinDLL("user32", use_last_error=True)
        user32.SendMessageTimeoutW.restype = ctypes.c_void_p
        user32.SendMessageTimeoutW.argtypes = [
            ctypes.c_void_p, ctypes.c_uint, ctypes.c_size_t, ctypes.c_wchar_p,
            ctypes.c_uint, ctypes.c_uint, ctypes.POINTER(ctypes.c_size_t),
        ]
        result = ctypes.c_size_t()
        user32.SendMessageTimeoutW(ctypes.c_void_p(0xFFFF), 0x1A, 0, "Environment",
                                   0x0002, 5000, ctypes.byref(result))
    except Exception:
        pass


def is_on_user_path(directory: Path, entries: list[str] | None = None) -> bool:
    if entries is None:
        entries = entries_of(read_user_path()[0])
    return any(same_path(entry, str(directory)) for entry in entries)


def choose_target() -> tuple[Path, bool]:
    """返回 (安装目录, 是否需要改 PATH)。"""
    entries = entries_of(read_user_path()[0])
    scripts = shortcut.python_scripts_dir()
    if scripts is not None and is_on_user_path(scripts, entries):
        return scripts, False
    dedicated = shortcut.dedicated_dir()
    return dedicated, not is_on_user_path(dedicated, entries)


def write_shim(directory: Path) -> Path:
    directory.mkdir(parents=True, exist_ok=True)
    shim = directory / shortcut.SHIM_NAME
    shim.write_text(
        SHIM_TEMPLATE.format(python=sys.executable,
                             cli=ROOT / "vrmmon" / "cli.py"),
        encoding="ascii", newline="\r\n")
    return shim


def show() -> int:
    raw, kind = read_user_path()
    kind_name = {winreg.REG_SZ: "REG_SZ",
                 winreg.REG_EXPAND_SZ: "REG_EXPAND_SZ"}.get(kind, str(kind))
    active = shortcut.active_shim()
    print(f"用户 PATH 类型   {kind_name}")
    print(f"用户 PATH 条目   {len(entries_of(raw))}")
    for path in shortcut.candidates():
        mark = "  <== 生效" if active == path else ""
        state = "存在" if path.exists() else "不存在"
        on_path = "在 PATH 中" if is_on_user_path(path.parent) else "不在 PATH 中"
        print(f"  {path}  [{state}, {on_path}]{mark}")
    return 0 if active else 1


def install() -> int:
    cli = ROOT / "vrmmon" / "cli.py"
    if not cli.exists():
        print(f"找不到 {cli}", file=sys.stderr)
        return 2

    target, need_path = choose_target()
    old = shortcut.dedicated_dir()

    # 换位置时把旧位置清理掉，避免两个同名命令
    if target != old:
        stale = old / shortcut.SHIM_NAME
        if stale.exists():
            stale.unlink()
            print(f"已删除旧位置的启动器 {stale}")

    shim = write_shim(target)
    print(f"启动器已写入   {shim}")

    raw, kind = read_user_path()
    BACKUP.write_text(raw, encoding="utf-8")
    entries = entries_of(raw)

    if need_path:
        if not is_on_user_path(target, entries):
            write_user_path(";".join(entries + [str(target)]), kind)
            broadcast_change()
            entries = entries + [str(target)]
            print(f"已追加到用户 PATH: {target}")
            print("注意：新增的 PATH 目录对已在运行的资源管理器不可见，"
                  "必要时注销/重启一次才生效。")
    else:
        print(f"{target} 本来就在用户 PATH 中，无需修改 PATH")

    # 若之前往 PATH 里加过专用目录，现在不用了就撤掉
    if target != old and is_on_user_path(old, entries):
        kept = [entry for entry in entries if not same_path(entry, str(old))]
        write_user_path(";".join(kept), kind)
        broadcast_change()
        print(f"已从用户 PATH 移除不再需要的 {old}")
    try:
        old.rmdir()
    except OSError:
        pass

    print()
    print("完成。请新开一个终端，然后试：")
    print("  vrmmon           启动界面（提权，完整传感器）")
    print("  vrmmon noadmin   普通权限启动（仅显卡/硬盘）")
    print("  vrmmon doctor    终端里看体检报告")
    print("  vrmmon where     看安装与权限状态")
    print("  vrmmon stop      请实例优雅退出")
    return 0


def uninstall() -> int:
    removed = False
    for path in shortcut.candidates():
        if path.exists():
            path.unlink()
            print(f"已删除 {path}")
            removed = True

    old = shortcut.dedicated_dir()
    raw, kind = read_user_path()
    entries = entries_of(raw)
    if is_on_user_path(old, entries):
        kept = [entry for entry in entries if not same_path(entry, str(old))]
        write_user_path(";".join(kept), kind)
        broadcast_change()
        print(f"已从用户 PATH 移除 {old}")
    try:
        old.rmdir()
    except OSError:
        pass

    if not removed:
        print("没有找到已安装的启动器")
    return 0


def main(argv: list[str] | None = None) -> int:
    for stream in (sys.stdout, sys.stderr):
        try:
            stream.reconfigure(encoding="utf-8", errors="replace")
        except (AttributeError, ValueError):
            pass

    parser = argparse.ArgumentParser(prog="install_shortcut",
                                     description="把 vrmmon 装进 PATH")
    parser.add_argument("--uninstall", action="store_true", help="卸载启动器")
    parser.add_argument("--show", action="store_true", help="只显示当前状态")
    args = parser.parse_args(argv)

    if sys.platform != "win32":
        print("仅支持 Windows", file=sys.stderr)
        return 2
    if args.show:
        return show()
    return uninstall() if args.uninstall else install()


if __name__ == "__main__":
    raise SystemExit(main())
